### ISSUE TITLE
Fixing (or eliminating?) ImprovedModelAdmin and ImprovedTabularInline

### ISSUE THREAD

**Issue by abarysh** [yeastphenome/yeastphenome.org#48] opened 2020-11-04 20:05 UTC
The custom admin models (ImprovedModelAdmin and ImprovedTabularInline) were created for a single purpose: to assign custom widgets to ForeignKey and ManyToMany fields displayed as raw_id_fields. The desired feature was that to display related objects as link to their change pages. Example: /admin/datasets/dataset/541/change/ (all ForeignKeys are displayed as raw_id_fields and have links to the corresponding objects).

Since Django 1.10, this feature is built in as default for ForeignKey fields. BUT (as far as I know) no such update has been made for ManyToMany fields. Hence, the need to keep ImprovedModelAdmin around. 

Problem: ImprovedModelAdmin is a bit buggy. Right now, it has trouble opening and closing popup windows after you click on the magnifying glass to add a new relation (the problem seems to be fixed when switching to standard admin.ModelAdmin). Example, clicking on the magnifying glass next to "Tested source" in dataset 541, opens 2 popups but neither of them shows anything. When the browser blocks popups, one new window opens (not a popup) but it doesn't close after you choose the correct object to link.

Desired outcome: ideally, avoid ImprovedModelAdmin all together. Alternatively, investigate the popup problem.

(Happy to provide more details if needed).

**Comment by vsoch** [comment] 2020-11-04 22:07
This is accurate, I just reproduce the issue by changing the DatasetAdmin to be basedoff of admin.ModelAdmin, and can confirm that we don't see names next to a many to many field (tags)

![image](https://user-images.githubusercontent.com/814322/98170353-10800b80-1eab-11eb-87ff-1e8bac1c5c5a.png)

and with the ImprovedModelAdmin we do

![image](https://user-images.githubusercontent.com/814322/98170404-28f02600-1eab-11eb-906d-7caaa3b65701.png)

So I think there are a couple of options, based on what I just tried. My intuition says that trying to mess around with controlling popups is going to be very hard, especially since people have different browse preferences and browsers change quite a bit. The simplest approach that lets you easily see the tags is to have a many to many select, which looks like this:

![image](https://user-images.githubusercontent.com/814322/98172429-9e112a80-1eae-11eb-8ec9-5ea8ded54899.png)

Another approach I just tried is to have an inline box (at the bottom) to add them one at a time. That looks like this.

![image](https://user-images.githubusercontent.com/814322/98172530-c731bb00-1eae-11eb-8d50-8acb8095a5be.png)

But actually there is a better option - if we let the field default to a ManytoMany and then we set filter_horizontal to indicate tags, we get a nice UI to filter/select on the left, and see the choices on the right:

![image](https://user-images.githubusercontent.com/814322/98172821-41623f80-1eaf-11eb-97e3-d3dc18000012.png)

I like the last one, since it readily shows the options, what is selected, and doesn't require any special classes.  I'll make the change for the datasets model in a PR, just that one admin view, and then we can discuss. We can then choose to implement it for others, or try something different. In case we want the inline, the code basically looks like this:

```python
class TagInline(admin.TabularInline):
    model = Dataset.tags.through
    verbose_name = u"Tag"
    verbose_name_plural = u"Tags"

class DatasetAdmin(admin.ModelAdmin):
    model = Dataset
    form = DatasetAdminForm
    save_on_top = True
    inlines = (
       TagInline,
    )
    fields = (
        "name",
        "paper",
        "conditionset",
        "medium",
        "control_conditionset",
..
```
And if we want the more simply multiple selection box, we just remove the filter_horizontal.

**Comment by abarysh** [comment] 2020-11-05 02:08
Yeah, I've gone through all of these options back at the time and unfortunately they won't work for most other cases. With tags, there's (for now) a relatively small number of options to choose from. But for other cases (e.g., the list of conditions in a conditionset) there're thousands of options (and growing). In such a situation, the inlines and the filter_horizontal options are both impractical (for choosing) and quite inefficient (slow down the page significantly). I think we'll need to stick to raw_id_fields... I just we just need to figure out how django implements its current raw_id_field widget for ForeignKey and adapt it to ManyToMany fields. There're a few code snippets online (which is where I got my original code for ImprovedModelAdmin etc.), I just think they need to be tested/adjusted for Django 3 (they were working ok on Django 1.9).

**Comment by vsoch** [comment] 2020-11-05 05:29
Ah understood! I'll take another look at this.

**Comment by vsoch** [comment] 2020-11-05 19:20
I'm testing using an updated ImprovedModelAdmin and standard admin.ModelAdmin, and for large lists (e.g., /admin/conditions/conditionset/2/change/) whether I choose the first or the second, the page is basically unload-able, and I think the slowness isn't about this particular admin class, but the custom generation of a list of datasets. Was this an issue before? I'm having a hard time working on this particular issue because I don't have a clear vision of what is desired - personally I like the horizontal layout that collapses the options and lets you still search over them easily (this one).

![image](https://user-images.githubusercontent.com/814322/98286310-0a4c6680-1f61-11eb-846f-e3056f147ec2.png)

But I gave it my best shot to follow your instruction and mimic what I see in the django.contrib.admin module to map the simple foreign key type to the many to many: https://github.com/yeastphenome/yeastphenome.org/pull/50. And here is a shot of a many to many on the Dataset model:

![image](https://user-images.githubusercontent.com/814322/98286483-50a1c580-1f61-11eb-9f8d-1d0ec00e527d.png)

I can't confidently say this is what is desired, but maybe it's in the right direction? @abarysh can you take a look?

**Comment by abarysh** [comment] 2020-11-05 20:08
I think we're almost there. Don't worry about /admin/conditions/conditionset/2/change/ for the time being, that's a separate issue. Let's focus on the Dataset admin page. 

You can check the desired outcome on the old implementation: http://yeastphenome.org/admin/datasets/dataset/16594/change/ (here, it works exactly as it should)

In summary, here're the key points:
1) the name of the related object (for ForeignKey) or objects (for ManyToMany) is displayed next to the raw_id field.
2) the name is a link to the corresponding change page.
3) when you click on the link, a window pops out where you can edit the related object. When you click Save, the pop up window closes and the current page refreshes.
4) when you click on the magnifying glass, a window pops out where you can choose a new related object. When you select the new object, the pop up window closes and the new raw_id appears in the TextInput box.

Does that make sense? Happy to chat in person, if that's easier.

**Comment by vsoch** [comment] 2020-11-05 20:51
Everything seems to work except for:

> when you click on the link, a window pops out where you can edit the related object. When you click Save, the pop up window closes and the current page refreshes.

The popup windows indicates that it's closing, but it doesn't actually close. I need to click and then close it. This is especially buggy to try and develop since the browse can vary hugely with popups. 

> when you click on the magnifying glass, a window pops out where you can choose a new related object. When you select the new object, the pop up window closes and the new raw_id appears in the TextInput box.

I find this really confusing because two popups appear, one to make it handy to add a new tag if I need, and a second to select one. But the page does update to include the new number, however it does not add the name and link until you click save, which is what I'd expect for behavior. After I click save, then the listing is updated with links:
 
![image](https://user-images.githubusercontent.com/814322/98294642-82208e00-1f6d-11eb-88a4-e92b6d1914a6.png)

(And don't worry, I added the second tag and then removed it, no bugs introduced!). 

It makes sense, but I think what I'm able to do trying to control popups (and seeing that my browser knows it should be closed but doesn't do it) is not something I know how to do. Maybe you have ideas? Do you want to look at the PR, run it locally, and see if you come up with something?

**Comment by abarysh** [comment] 2020-11-05 20:53
Yeah, sounds good. I'll check out the PR later today and let you know if I come up something.

**Comment by vsoch** [comment] 2020-11-05 20:57
Thank you! And strange, I just tested the same view again, and the popup did close this time (at least one of them). If I can reproduce the message that I saw earlier for "closing popup" I'll include it here.

**Closed as completed** 2020-11-09 19:54 UTC
