### ISSUE TITLE
Sorting of phenotypes/reporters in the phenotypes explorer

### ISSUE THREAD

**Issue by abarysh** [yeastphenome/yeastphenome.org#77] opened 2020-12-10 02:10 UTC
Papers -> Explorer the "phenotypes" column doesn't seem to sort correctly. The paper.phenotypes() function does seem to return an ordered list, and then applied with join_and_more we'd only have a subset. And the order query also targets dataset__phenotype__observable__name, which should be the same field. So I'm not sure why the list doesn't appear sorted - could it be related to capital letters? E.g., look at /papers/?query=growth and sort, the main ones out of order start with a capital A. And if so, should there be a convention about using / not using them?

**Comment by vsoch** [comment] 2020-12-10 02:11
I can try again, but I’m not sure I have any new ideas for how to fix this.

**Comment by vsoch** [comment] 2020-12-10 02:12
I’ll try again tomorrow and hope that I’m more clever than earlier today! 😅

**Comment by vsoch** [comment] 2020-12-10 18:23
I gave another shot at this, no luck. I tried [lower](https://docs.djangoproject.com/en/3.1/ref/models/database-functions/#django.db.models.functions.Lower) but this seems not to work for related fields, and I also tried annotating the field then doing lower (no luck). Finally, I tried extra [ref](http://naorrosenberg.blogspot.com/2011/04/django-models-orderby-charfield-case.html) but again it didn't seem to work with a related/nested field.

**Comment by abarysh** [comment] 2020-12-10 20:57
Just pushed an update to PR #81 that fixes this. The issue was that the sorting and the displaying of the results used different values. The sorting was done on STRING_AGG which aggregates only observable names that match the search criteria (e.g., "growth"). However, the displaying was done on all observables for that paper. As a result, an observable list that starts with "Average ..." was out of order. 

Having thought about it, I figured that it does make sense to display the results of STRING_AGG (at least for now). So I updated the papers/templates/papers/papers_table.html file to reflect that.

Also, made similar updates to the conditions column in the same table. It had a very bizarre behavior upon sorting. Now should be fixed.

**Comment by vsoch** [comment] 2020-12-10 21:05
Great! The StringAgg actually wasn't there before, I was messing around with it this morning seeing if it would help (and it didn't really change anything). That does make sense though! I'll deploy to staging and see if it works!

**Comment by vsoch** [comment] 2020-12-11 03:53
It looks like we have this same issue (with capital letters) for:

 - Phenotypes --> reporters
 - Phenotypes --> papers

And I'll add to the list any more that I see - I should have a PR sometime tomorrow morning with the final fixes for #83

**Comment by vsoch** [comment] 2020-12-12 16:54
The above two tables sorting still has the same issue. @abarysh can you reproduce what you did for phenotypes there, or tell me how you did it and I can try?

**Comment by abarysh** [comment] 2020-12-12 23:14
Yep. So, for Phenotypes --> reporters it's an easy fix (will push a commit as part of a PR coming today). But for Phenotypes --> papers, there was some mysterious stuff happening  -- e.g., when you sort by 1 column you get one set of paper_lists; when you sort by the paper column, a random and out of order entry appears. I removed 2 fields from the phenotype search (in `phenotypes/search.py`) and the random entry stopped appearing.  Not sure what was happening (I couldn't reproduce it with a raw SQL query to the database), but the problem seems to be fixed now. I suggest we consider this fixed for now, and revisit later (if we have better ideas).

**Comment by vsoch** [comment] 2020-12-12 23:18
Sounds good! So if you don't want to do any database table renaming foo before deploying to staging, I can deploy the current version to staging after your commits are pushed. Ping me in the PR when you are ready / decided!

**Comment by abarysh** [comment] 2020-12-12 23:54
This can be closed after PR #96 is merged.

**Comment by vsoch** [comment] 2020-12-13 00:13
The papers list is still a little weird (e.g., see Dalton, Anand, etc. coming after J)
![image](https://user-images.githubusercontent.com/814322/101999744-4cbe3d00-3c9d-11eb-94e1-a5ed7d4e5147.png)

But I think it's a small thing and I'm good with closing this for now if you are too!

**Comment by abarysh** [comment] 2020-12-13 00:16
Yeah, there's some mysterious stuff happening here. E.g., if you look up the Dalton paper, does it actually match the search criteria? In the one case I was investigating, the phenotype in question was not matching the search criteria and not even supposed to be in the results. Indeed, if I ran the corresponding SQL query in the database, that phenotype wasn't there. But I can't figure out why it does come up on the website.

**Comment by vsoch** [comment] 2020-12-17 18:29
okay I think I have a fix for this - just using the observable.paper_list instead of observable.papers()

**Comment by abarysh** [comment] 2020-12-18 17:30
Tested on staging -- fixed

**Closed as completed** 2020-12-18 19:49 UTC
Labels: bug
